services:
    poker.front:
        image: node:22
        working_dir: /src
        ports:
            - '${APP_PORT:-80}:3000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
        networks:
            - poker_app
        container_name: poker-front
        volumes:
            - './front:/src'
        command: sh -c "npm install && npm run start"

    poker.back:
        image: node:22
        working_dir: /src
        container_name: poker-api
        networks:
            - poker_app
        volumes:
            - './api:/src'
        command: sh -c "npm install && npm run start:dev"
        ports:
        - "3000:3000"
networks:
    poker_app:
        external: true
volumes:
    poker_data:
        driver: local
